name: Test workflow
on: push
jobs:
 hola_mundo:
   runs-on: ubuntu-latest
  
   steps:
     - name: Bajar código 
       uses: actions/checkout@v4

     - name: Instalar pytest
       run: pip install pytest

     - name: Ejecutar test
       run: pytest test.py
